server:
  port: 9090
spring:
  datasource:
    name: databaseName
    url: jdbc:mysql://*.*.*.*/databaseName?useUnicode=true&characterEncoding=utf-8
    username: databaseUser
    password: databasePassword
    # 使用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 3000
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.rokid.jupiter.dao.entity

pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false

# 日志配置
#logging:
#  config:
#    classpath:logback.xml

server.max-http-header-size: 100MB

# run的时候加上参数environment->program arguments :--spring.profiles.active=dev

